ControleDeContatos/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleDeContatos.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do contato")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o e-mail do contato")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Digite o celular do contato")]
        [Phone(ErrorMessage = "O celular informado não é valido!")]
        public string Celular { get; set; }
    }
}

ControleDeContatos/Models/ErrorViewModel.cs
using System;

namespace ControleDeContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ControleDeContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }
        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();

            return View(contatos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar o contato!";
                }

                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar o contato, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(contato);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar o contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", contato);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar o contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
    }
}

ControleDeContatos/Controllers/HomeController.cs
using ControleDeContatos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControleDeContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleDeContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação apagar o contato";
}

<div class="text-center">
    <h3>Realmente deseja apagar o contato(@Model.Nome)?</h3>
</div>

<a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Contato" role="button">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-action="Apagar" asp-controller="Contato" asp-route-id="@Model.Id" role="button" >Confirmar exclusão</a>

ControleDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criar contato";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar contato</h1>
</div>


<form asp-controller="Contato" asp-action="Criar" methotd="post">

    <div class="form-group">
        <label for="nome" class="col-form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email" class="col-form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular" class="col-form-label">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Contato" role="button">Voltar</a>

</form>

ControleDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar contato";
}

<div class="text-center">
    <h1 class="display-4">Editar contato</h1>
</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome" class="col-form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email" class="col-form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular" class="col-form-label">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Contato" role="button">Voltar</a>

</form>

ControleDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de contatos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
             <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
             @TempData["MensagemSucesso"]
         </div>
    }


    @if (TempData["MensagemErro"] != null)
    {
         <div class="alert alert-danger" role="alert">
              <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
              @TempData["MensagemErro"]
         </div>
    }

    <br />

    <h1 class="display-4">Listagem de contatos</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Celular</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ContatoModel contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ControleDeContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de contatos</p>
</div>

ControleDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>